#!/usr/bin/python
import argparse
import server
from app import utils

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run WordCount Validator")
    parser.add_argument("setup", help="Initialize database", nargs="?")
    parser.add_argument("test", help="Run testcases", nargs="?")

    args = parser.parse_args()
    if args.setup:
        print "Setting up database ...",
        server.setup_and_seed_db()
        print "Done."
    if args.test:
        print "Running testcases"
    else:
      server.app.run(port=8000)
