#!/usr/bin/python
import argparse
import server
from app import utils
from tests import unittests
from tests import integration
import unittest

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Run WordCount Validator")
    parser.add_argument("-setup", help="Initialize database", default=False, action="store_true")
    parser.add_argument("-test", help="Run testcases", default=False, action="store_true")

    args = parser.parse_args()
    if args.setup:
        print "Setting up database ...",
        server.setup_db()
        print "Done."
    elif args.test:
        unit_suite = unittest.TestLoader().loadTestsFromTestCase(unittests.TestWordCountUtils)
        unittest.TextTestRunner(verbosity=2).run(unit_suite)
        integration_suite = unittest.TestLoader().loadTestsFromTestCase(integration.TestWordCountApp)
        unittest.TextTestRunner(verbosity=2).run(integration_suite)
    else:
        server.app.run(port=8000)
